"""add validations table

Revision ID: a5b261d0c8d2
Revises: ef9c3e56e17a
Create Date: 2026-09-11 10:04:47.712306

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "a5b261d0c8d2"
down_revision: str | None = "ef9c3e56e17a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_validations_invoice_id"), ["invoice_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("validations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_validations_invoice_id"))

    op.drop_table("validations")
    # ### end Alembic commands ###
