"""add vendors, purchase orders, po lines, invoice matches

Revision ID: ef9c3e56e17a
Revises: 81057ea53af5
Create Date: 2026-09-11 09:04:48.036063

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "ef9c3e56e17a"
down_revision: str | None = "81057ea53af5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("legal_name", sa.String(length=500), nullable=False),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vendors_tax_id"), ["tax_id"], unique=False)

    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("po_number", sa.String(length=128), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_po_number"), ["po_number"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_purchase_orders_vendor_id"), ["vendor_id"], unique=False
        )

    op.create_table(
        "invoice_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("vendor_match_method", sa.String(length=32), nullable=False),
        sa.Column("vendor_confidence", sa.Float(), nullable=False),
        sa.Column("vendor_candidates", sa.JSON(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=True),
        sa.Column("po_match_method", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["po_id"], ["purchase_orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoice_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invoice_matches_invoice_id"), ["invoice_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_invoice_matches_po_id"), ["po_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_invoice_matches_vendor_id"), ["vendor_id"], unique=False
        )

    op.create_table(
        "po_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["po_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("po_lines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_po_lines_po_id"), ["po_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("po_lines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_po_lines_po_id"))

    op.drop_table("po_lines")
    with op.batch_alter_table("invoice_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_matches_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_matches_po_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_matches_invoice_id"))

    op.drop_table("invoice_matches")
    with op.batch_alter_table("purchase_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_orders_vendor_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_orders_po_number"))

    op.drop_table("purchase_orders")
    with op.batch_alter_table("vendors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vendors_tax_id"))

    op.drop_table("vendors")
    # ### end Alembic commands ###
